'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { Crosshair, LayoutDashboard, ChartNoAxesColumnIncreasing, Smartphone, CalendarDays, FileSearch, Plus, Download, ArrowUpRight, Settings, MapPin, Search, ShieldCheck } from 'lucide-react';
import { Campaign, demoPoints, readDrafts } from '../lib/campaign';
import CampaignBuilder from './campaign-builder';
import EvidencePanel from './evidence-panel';
const ObservationMap=dynamic(()=>import('./observation-map'),{ssr:false,loading:()=> <div className="map-loading">Loading geographic map…</div>});
const storageKey='stakeout.search.campaign-drafts.v1';
const navItems=[['Overview',LayoutDashboard],['Campaigns',ChartNoAxesColumnIncreasing],['Devices',Smartphone],['Schedules',CalendarDays],['Evidence',FileSearch],['Settings',Settings]] as const;
export default function CommandCenter(){
 const [nav,setNav]=useState('Campaigns');const [tab,setTab]=useState('Overview');const [selected,setSelected]=useState('MB-05');const [builder,setBuilder]=useState(false);const [drafts,setDrafts]=useState<Campaign[]>([]);const [draftId,setDraftId]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{try{setDrafts(readDrafts(localStorage.getItem(storageKey)));}catch{setNotice('Browser storage is unavailable. Export drafts to keep a copy.');}},[]);
 const active=drafts.find(c=>c.id===draftId);const point=demoPoints.find(p=>p.id===selected)!;
 function save(c:Campaign){const next=[c,...drafts];setDrafts(next);try{localStorage.setItem(storageKey,JSON.stringify(next));setNotice('Campaign draft saved in this browser. No device tasks have been scheduled.');}catch{setNotice('Draft exists only in memory. Export it before closing this page.');}setDraftId(c.id);setBuilder(false);setNav('Campaigns');setTab('Overview');}
 function exportDraft(){if(!active)return;const url=URL.createObjectURL(new Blob([JSON.stringify(active,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stakeout-campaign-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const currentTab=nav==='Schedules'?'Schedule':nav==='Devices'?'Devices':tab;
 return <div className="app-shell"><div className="preview-bar"><strong>DESIGN PREVIEW · ILLUSTRATIVE DATA</strong><span>Managed mobile search observation <i/> No live device connection</span></div><aside className="sidebar"><a className="brand" href="/"><Crosshair size={36}/><div>STAKEOUT<span>Search observatory</span></div></a><nav aria-label="Main navigation">{navItems.map(([name,Icon])=><button key={name} className={nav===name?'nav-item active':'nav-item'} onClick={()=>{setNav(name);setNotice('');}} aria-current={nav===name?'page':undefined}><Icon size={21}/>{name}</button>)}</nav><div className="sidebar-foot"><ShieldCheck size={18}/><div>Managed infrastructure<span>Your market. Our device fleet.</span></div></div></aside>
 <main><div className="breadcrumb">Campaigns <span>/</span> {active?.location||'Miami Beach'}</div><header className="page-heading"><div><h1>Campaign Command Center</h1><p>{active?.business||'South Beach Auto Accident Attorney'}</p></div><button className="button primary" onClick={()=>setBuilder(true)}><Plus size={18}/>New campaign</button></header>
 <div className="campaign-controls"><span className="chip"><CalendarDays size={17}/>{active?.days||45}-day campaign</span><span className="chip"><Smartphone size={17}/>{active?.devices||5} {active?'requested':'sample'} devices</span><span className="chip"><Search size={17}/>Chrome · Local Finder</span><label className="campaign-select"><span className="sr-only">Select campaign</span><select value={draftId} onChange={e=>setDraftId(e.target.value)}><option value="">Miami Beach · sample campaign</option>{drafts.map(c=><option key={c.id} value={c.id}>{c.business} · draft</option>)}</select></label></div>
 {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>Dismiss</button></div>}
 {nav==='Settings'?<section className="panel settings"><h2>Managed service settings</h2><p>Customers do not need a DuoPlus account or API key.</p><dl><dt>Device provider</dt><dd>Company-managed DuoPlus · connection pending</dd><dt>ISP proxies</dt><dd>Managed by Stakeout · customer proxies optional</dd><dt>Billing</dt><dd>Not connected · no payments accepted in this preview</dd><dt>Campaign storage</dt><dd>Local browser drafts · not synced to an account</dd></dl></section>:active?<section className="panel draft-detail"><div className="panel-heading"><h2>Campaign draft</h2><span className="tag">Not activated</span></div><p>This plan is ready for review. Billing, provisioning, and automated execution are not connected in this preview.</p><div className="draft-stats"><div><strong>{active.warmup}</strong><span>warmup days</span></div><div><strong>{active.days-active.warmup}</strong><span>tracking days</span></div><div><strong>{active.concurrency}</strong><span>requested parallel slots</span></div></div><h3>Keywords</h3><div className="keyword-list">{active.keywords.map(k=><span className="chip" key={k}>{k}</span>)}</div><h3>Surfaces</h3><p>{active.surfaces.join(' · ')}</p><a href={active.listing} target="_blank" rel="noreferrer" className="text-link">Open business listing <ArrowUpRight size={16}/></a><footer><button className="button" onClick={exportDraft}><Download size={17}/>Export draft</button><button className="button" onClick={()=>setDraftId('')}>View sample workspace</button></footer></section>:<>
 <div className="lifecycle"><div className="phase-track"><div className="warmup">Warmup · Days 1–14</div><div className="tracking">Tracking · Days 15–45</div><div className="day-marker"><span>Day 18</span><i/></div></div><div className="phase-labels"><span>Day 1</span><span>Day 15</span><span>Day 45</span></div></div>
 <div className="metrics"><div><Crosshair/><section><span>Observation coverage</span><strong>84 / 90</strong></section><small>sample locations</small></div><div><Smartphone/><section><span>Assigned devices</span><strong>5</strong></section><small>sample devices</small></div><div><FileSearch/><section><span>Evidence captured</span><strong>84 runs</strong></section><small>illustrative total</small></div></div>
 <nav className="tabs" aria-label="Campaign views">{['Overview','Schedule','Rank map','Devices'].map(t=><button key={t} className={currentTab===t?'selected':''} aria-pressed={currentTab===t} onClick={()=>{setTab(t);setNav('Campaigns');}}>{t}</button>)}</nav>
 {nav==='Evidence'?<EvidencePanel point={point}/>:currentTab==='Devices'?<section className="panel"><div className="panel-heading"><h2>Assigned devices</h2><span className="muted">Illustrative inventory</span></div><div className="table-scroll"><table><thead><tr><th>Device</th><th>Market</th><th>Connection</th><th>Account cohort</th></tr></thead><tbody>{[1,2,3,4,5].map(n=><tr key={n}><td><Smartphone size={16}/>Device 0{n}</td><td>Miami Beach, FL</td><td><span className="muted">Not connected</span></td><td>14-day sample warmup</td></tr>)}</tbody></table></div></section>:currentTab==='Schedule'?<Schedule expanded onSelect={()=>{setNav('Evidence');}}/>:<><div className="observation-grid"><section className="panel visibility"><div className="panel-heading"><h2>Visibility by location</h2><span className="chip small"><Search size={15}/>car accident lawyer near me</span></div><ObservationMap selected={selected} onSelect={setSelected}/><div className="point-selector" aria-label="Observation locations">{demoPoints.map(p=><button key={p.id} aria-pressed={selected===p.id} className={selected===p.id?'selected':''} onClick={()=>setSelected(p.id)}>{p.id}<strong>{p.rank===null?'—':`#${p.rank}`}</strong></button>)}</div></section><EvidencePanel point={point}/></div><Schedule onSelect={()=>setNav('Evidence')}/></>}
 </>}
 <footer className="workspace-footer"><span>One observation, with the context to understand it.</span><span>Preview data is not a customer report.</span></footer></main>{builder&&<CampaignBuilder onClose={()=>setBuilder(false)} onSave={save}/>}</div>;
}
function Schedule({expanded=false,onSelect}:{expanded?:boolean;onSelect:()=>void}){const rows=[['Slot 1','Device 03','Chrome search','10:10 AM – 10:40 AM',30],['Slot 2','Device 01','Maps observation','10:15 AM – 10:45 AM',36],['Slot 3','Device 05','Warmup routine','10:20 AM – 10:50 AM',43]] as const;return <section className="panel schedule"><div className="panel-heading"><h2>Execution schedule</h2><span className="muted">Example day · America/New_York</span></div>{expanded&&<p className="schedule-description">Sample allocation of three concurrent slots. These tasks have not been submitted to a device provider.</p>}<div className="table-scroll"><table><thead className="sr-only"><tr><th>Slot</th><th>Device</th><th>Task</th><th>Status</th><th>Time block</th><th>Time</th></tr></thead><tbody>{rows.map(([slot,device,task,time,width])=><tr key={slot}><td>{slot}</td><td><Smartphone size={16}/>{device}</td><td><button className="row-action" onClick={onSelect}>{task}<ArrowUpRight size={14}/></button></td><td><span className="tag">Sample task</span></td><td className="time-bar"><div><i style={{width:`${width}%`}}/></div></td><td className="muted">{time}</td></tr>)}</tbody></table></div><footer>3 example concurrent slots · 5 sample devices · no live schedule</footer></section>;}
